export default  {
    GET_USERS_DATA_FETCH: 'GET_USERS_DATA_FETCH',
    GET_USERS_DATA_SUCCESS: 'GET_USERS_DATA_SUCCESS',
    GET_USERS_DATA_ERROR: 'GET_USERS_DATA_ERROR',
    GET_HOBBIES_DATA_FETCH: 'GET_HOBBIES_DATA_FETCH',
    GET_HOBBIES_DATA_SUCCESS: 'GET_HOBBIES_DATA_SUCCESS',
    GET_HOBBIES_DATA_ERROR: 'GET_HOBBIES_DATA_ERROR',
    ADD_USER_FETCH: 'ADD_USER_FETCH',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_ERROR: 'ADD_USER_ERROR',
    SELECT_USER: 'SELECT_USER',
    ADD_HOBBY_FETCH: 'ADD_HOBBY_FETCH',
    ADD_HOBBY_SUCCESS: 'ADD_HOBBY_SUCCESS',
    ADD_HOBBY_ERROR: 'ADD_HOBBY_ERROR',
    DELETE_HOBBY_FETCH: 'DELETE_HOBBY_FETCH',
    DELETE_HOBBY_SUCCESS: 'DELETE_HOBBY_SUCCESS',
    DELETE_HOBBY_ERROR: 'DELETE_HOBBY_ERROR'
}